# Generated by Django 4.0.5 on 2022-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.FileField(max_length=250, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='image',
            field=models.FileField(max_length=250, upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='content',
            table='contents',
        ),
        migrations.AlterModelTable(
            name='style',
            table='styles',
        ),
    ]
