# Generated by Django 4.0.5 on 2022-07-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_content_image_remove_style_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content-image',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='style-image',
            new_name='style',
        ),
    ]
